[theme]
primaryColor = "#ff4b4b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[server]
maxUploadSize = 200
maxMessageSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false
